services:
  - type: web
    name: counter-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python init_db.py && python app.py"
    envVars:
      - key: DATABASE_URL
        value: sqlite:///database.db

